# Generated by Django 4.0 on 2022-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Restaurant', 'Restaurant')], max_length=10),
        ),
    ]
